export type DatePickerProps = {
	value?: Date | null;
	defaultValue?: Date;
	open?: boolean;
	disabled?: boolean;
	readOnly?: boolean;
	format?: string;
	views?: ('year' | 'month' | 'day')[];
	openTo?: 'year' | 'month' | 'day';
	minDate?: Date;
	maxDate?: Date;
	shouldDisableDate?: (date: Date) => boolean;
	shouldDisableMonth?: (date: Date) => boolean;
	shouldDisableYear?: (date: Date) => boolean;
	disableFuture?: boolean;
	disableHighlightToday?: boolean;
	disableOpenPicker?: boolean;
	disablePast?: boolean;
	displayWeekNumber?: boolean;
	fixedWeekNumber?: number;
	loading?: boolean;
	monthsPerRow?: 3 | 4;
	orientation?: 'landscape' | 'portrait';
	reduceAnimations?: boolean;
	showDaysOutsideCurrentMonth?: boolean;
	showToolbar?: boolean;
	timezone?: string;
	toolbarFormat?: string;
	toolbarPlaceholder?: string;
	toolbarTitle?: string;
	class?: string;
};
