#!/bin/bash

# This script builds the component index file for the library.

# The directory where the components are located.
COMPONENTS_DIR="src/lib/components"

# The output file for the component index.
INDEX_FILE="$COMPONENTS_DIR/index.ts"

# Start with a clean index file.
echo "// This file is auto-generated by build-lib.sh. Do not edit." > "$INDEX_FILE"
echo "" >> "$INDEX_FILE"

# Loop through each component directory.
for component in "$COMPONENTS_DIR"/*/; do
  # Check if the directory contains an index.ts file.
  if [ -f "${component}index.ts" ]; then
    # Get the component name from the directory path.
    componentName=$(basename "$component")
    echo "Exporting component: $componentName"
    # Append the export statement to the index file.
    echo "export * from './$componentName';" >> "$INDEX_FILE"
  fi
done

echo "" >> "$INDEX_FILE"
echo "Component index build complete."
