export type BoxProps = {
	m?: number | string;
	mt?: number | string;
	mr?: number | string;
	mb?: number | string;
	ml?: number | string;
	mx?: number | string;
	my?: number | string;
	p?: number | string;
	pt?: number | string;
	pr?: number | string;
	pb?: number | string;
	pl?: number | string;
	px?: number | string;
	py?: number | string;
	display?: string;
	flexDirection?: string;
	flexWrap?: string;
	justifyContent?: string;
	alignItems?: string;
	alignContent?: string;
	order?: number;
	flexGrow?: number;
	flexShrink?: number;
	alignSelf?: string;
	width?: number | string;
	height?: number | string;
	maxWidth?: number | string;
	maxHeight?: number | string;
	minWidth?: number | string;
	minHeight?: number | string;
	bgcolor?: string;
	color?: string;
	zIndex?: number;
	position?: string;
	top?: number | string;
	right?: number | string;
	bottom?: number | string;
	left?: number | string;
	boxShadow?: number | string;
	class?: string;
};
