import type { Snippet, $bindable } from '$lib/internal/types.js';

export type AutocompleteProps<T> = {
	options: Array<T>;
	value: $bindable<T | T[] | null>;
	inputValue: $bindable<string>;
	multiple?: boolean;
	freeSolo?: boolean;
	disableClearable?: boolean;
	clearOnBlur?: boolean;
	clearOnEscape?: boolean;
	disabled?: boolean;
	loading?: boolean;
	loadingText?: string;
	noOptionsText?: string;
	open?: $bindable<boolean>;
	autoComplete?: boolean;
	autoHighlight?: boolean;
	autoSelect?: boolean;
	blurOnSelect?: boolean | 'touch' | 'mouse';
	clearText?: string;
	closeText?: string;
	defaultValue?: T | T[];
	disableCloseOnSelect?: boolean;
	disableListWrap?: boolean;
	disablePortal?: boolean;
	filterSelectedOptions?: boolean;
	forcePopupIcon?: boolean | 'auto';
	fullWidth?: boolean;
	getOptionDisabled?: (option: T) => boolean;
	getOptionLabel?: (option: T) => string;
	groupBy?: (option: T) => string;
	handleHomeEndKeys?: boolean;
	id?: string;
	includeInputInList?: boolean;
	inputMode?: string;
	isOptionEqualToValue?: (option: T, value: T) => boolean;
	limitTags?: number;
	openOnFocus?: boolean;
	openText?: string;
	readOnly?: boolean;
	selectOnFocus?: boolean;
	size?: 'small' | 'medium';
	cx?: object;
	onchange?: (value: T | T[], reason: string) => void;
	oninputchange?: (value: string, reason: string) => void;
	onopen?: () => void;
	onclose?: (reason: string) => void;
	children?: Snippet;
	option?: Snippet<[T]>;
	tag?: Snippet<[T]>;
	loadingSnippet?: Snippet;
	noOptions?: Snippet;
	popupIcon?: Snippet;
	clearIcon?: Snippet;
};
