export type DataGridProps = {
	rows?: any[];
	columns?: any[];
	autoHeight?: boolean;
	autoPageSize?: boolean;
	checkboxSelection?: boolean;
	density?: 'comfortable' | 'compact' | 'standard';
	disableColumnFilter?: boolean;
	disableColumnMenu?: boolean;
	disableColumnSelector?: boolean;
	disableDensitySelector?: boolean;
	disableMultipleColumnsFiltering?: boolean;
	disableMultipleColumnsSorting?: boolean;
	disableMultipleRowSelection?: boolean;
	disableRowSelectionOnClick?: boolean;
	disableVirtualization?: boolean;
	editMode?: 'cell' | 'row';
	filterMode?: 'client' | 'server';
	getCellClassName?: (params: object) => string;
	getRowClassName?: (params: object) => string;
	getRowHeight?: (params: object) => number | 'auto' | null;
	getRowId?: (row: object) => string | number;
	headerHeight?: number;
	hideFooter?: boolean;
	hideFooterPagination?: boolean;
	hideFooterRowCount?: boolean;
	hideFooterSelectedRowCount?: boolean;
	isCellEditable?: (params: object) => boolean;
	isRowSelectable?: (params: object) => boolean;
	keepNonExistentRowsSelected?: boolean;
	loading?: boolean;
	page?: number;
	pageSize?: number;
	pageSizeOptions?: number[];
	pagination?: boolean;
	paginationMode?: 'client' | 'server';
	rowBuffer?: number;
	rowCount?: number;
	rowHeight?: number;
	rowSelection?: boolean;
	rowSpacingType?: 'border' | 'margin';
	rowThreshold?: number;
	scrollbarSize?: number;
	scrollEndThreshold?: number;
	showCellVerticalBorder?: boolean;
	showColumnVerticalBorder?: boolean;
	sortingMode?: 'client' | 'server';
	sortingOrder?: ('asc' | 'desc')[];
	treeData?: boolean;
	class?: string;
};
